### ISSUE TITLE
meta README

### ISSUE THREAD

**Issue by undoingtech** [undoingtech/vidnotes#28]
**Describe issue with current documentation.**

All documentation describes Vidnotes.  I intended this project to be a sample.  I need another document that describes how I made Vidnotes and what my process was.

meta README should make it easy for recruiters to view significant changes and decisions 

**Suggest what new documentation should say.**

meta README should contain : 
- [x] link to scan of my notebook
- [x]  link to issues concerning first draft of vidnotes documentation
- [x]  link to issue concerning editing
- [x]  link to before and after first draft (first draft vs current version)
- [x]  links to history of each file
- [x] short rationale/explanation of organization of this project
- [x] intro

**Comment by undoingtech** [comment]
- [ ] There is not a way I can find to easily view the changes of an individual file commit by commit.  I will omit the history for each file.  It was one of the least useful things in this document anyway.  **Remove history links.**

- [ ] **Add links** to repo at certain stages: first draft complete, revision complete, substantive editing complete, copyediting complete, proofreading complete, all editing complete (same as proofreading), current.

- [ ] **Add forecasting** of some kind in the intro.  Can be paragraph or TOC.

- [ ] It would probably be more useful to **add a big table** for all the first draft issues and their associated commits.  The link to the first draft issues can still be there at the top.  Maybe also add links to repo at those points.

**Comment by undoingtech** [comment]
## Organization

- introduction
- sections
    - tasks, changes, and snapshots
    - organization of vidnotes
    - what i could change
- conclusion - include contact info?

**Comment by undoingtech** [comment]
- Work Done section is a hot mess.  
- I am not sure how to best include links to first issues, big editing issue, wiki, and first-draft to edited diff
- Do I need a conclusion?  What would be in it?

**Comment by undoingtech** [comment]
Perhaps add a section in the Work Done section. **Conveniece Links**.  Something like that.

This section should include links to show the work done:
- vidnotes documentation
- wiki link
- all issues
- all first draft issues
- editing issue
- first draft to edited diff
- notebook

**Comment by undoingtech** [comment]
Add links to quick links section:
- first draft complete snapshot
- editing complete snapshot

**Comment by undoingtech** [comment]
### Editing

Rename "Diff for master...08" to "Changes after Editing Phase" or something like that.

Add link to all editing changes together.

Then redo intro.

**Comment by undoingtech** [comment]
## Revision

### Review rhetorical situation
- subject is the project itself
- purpose is to make it easy to see changes to the project and know why those changes were made
- purpose is to make it easy to view changes to the project and understand the rationale behind the changes
- purpose is to let the reader see the project at different stages, show changes from one stage to another, and show the reasons behind those changes
- purpose is the let the reader see snapshots and changes 
- purpose is to let readers easily view decisions, snapshots, and changes in the project
- purpose is to make it easy for readers to view decisions made regarding the project and  view the resulting changes 
**screw it, purpose stays the same**
- primary reader is a recruiter/hiring person who may or may not be knowledgeable of github and git
- context of use - changes????

I do not think the rhetorical situation has changed very much since I last reviewed it.

### Does this document describe the subject?  Has subject changed/evolved?
- all sections are about the project and the decisions of the project in some way
- subject of "My work on vidnotes" has stayed the same

### Does this document fulfill its purpose?  Has purpose changed/evolved?
- document mostly fulfills purpose
- document provides links to issues (decisions) and snapshots and diffs (changes)

### Is there any more need-to-know info?
- the editing table needs another column for "Notes" with links to editing comments
- still need forecasting in the intro 

### How can document better address readers' needs?
- increase raiablility.  make it SUPER easy for readeres to see what changes or decisions they want to see
- limit quick links to most significant chages/decisions.  put other links somewhere else (at the end)
- change word "issues" to "tasks"
- make better headings for "First Draft Issues" and "Editing" sections

**Comment by undoingtech** [comment]
## Substantive

### Are there any gaps in content?
- in Organization of the Project section, make "Github issues" a link to all github issues.
- TOC links need to be updated and filled in

### Is there non-need-to-know info?
- non that i see right now

### Are there deviations from organizational pattern?
- quick links should be in introduction
- introduction starts with title and not ## Introduction header.  I am okay with that

### Good intro and conclusion?
- intro is fine to me.  i cannot see a reason to add anything else to it
- i do not see a reason to add a conclusion

### are headers good?  can they be more raidable?
- headers were addressed in Revision comment above
